version: '3.2'

services:
  profile:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_USERNAME
      - DB_PASSWORD
      - DB_NAME
      - DB_HOSTNAME=postgres
      - DB_PORT=5432
    links:
      - postgres:postgres
  postgres:
    image: postgres:9.6.2
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USERNAME=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}